version: "2"
services:
  wonderlays:
    container_name: wonderlays
    restart: always
    build: .
    networks:
      - web
      - default
    expose:
      - "8383"
    labels:
      - "traefik.backend=my-awesome-app-app"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:wonderlays.akj.io"
      - "traefik.enable=true"
      - "traefik.port=8383"
      - "traefik.default.protocol=http"

networks:
  web:
    external: true