version: "3"
services:
  wonderlays_api:
    container_name: wonderlays_api
    restart: always
    build: .
    networks:
      - web
      - default
    ports:
      - "8383:8383"
    expose:
      - "8383"
    labels:
      - "traefik.backend=wonderlays_api" 
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:wonderlays.akj.io"
      - "traefik.enable=true"
      - "traefik.port=8383"
      - "traefik.default.protocol=https"

  wonderlays_db:
    image: mongo
    networks:
      - web
      - default
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

networks:
  web:
    external: true